# Generated by Django 5.2.16 on 2026-07-31 09:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('reference_type', models.CharField(max_length=40)),
                ('reference_id', models.UUIDField()),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(null=True)),
                ('status', models.CharField(default='DRAFT', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('vat_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cost_of_goods_sold', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('gross_margin_percentage', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.customer')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('sales_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.location')),
                ('salesperson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch', models.CharField(blank=True, max_length=80)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.finishedproduct')),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesinvoice')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.unitofmeasurement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('return_number', models.CharField(max_length=50, unique=True)),
                ('return_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(default='DRAFT', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('vat_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credit_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.customer')),
                ('original_sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesinvoice')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('return_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch', models.CharField(blank=True, max_length=80)),
                ('sold_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('previously_returned_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('return_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('condition', models.CharField(choices=[('SALEABLE', 'Saleable'), ('DAMAGED', 'Damaged'), ('EXPIRED', 'Expired'), ('QUALITY_ISSUE', 'Quality_Issue')], max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.finishedproduct')),
                ('original_sales_invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesinvoiceitem')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesreturn')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
