# Generated by Django 5.2.16 on 2026-07-31 09:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=160)),
                ('employee_code', models.CharField(max_length=40, unique=True)),
                ('role', models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('PURCHASE', 'Purchase'), ('PRODUCTION', 'Production'), ('WAREHOUSE', 'Warehouse'), ('SALES', 'Sales'), ('ACCOUNTS', 'Accounts'), ('MANAGER', 'Manager')], max_length=30)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('can_access_all_locations', models.BooleanField(default=False)),
                ('allowed_modules', models.JSONField(blank=True, default=list)),
                ('can_override_negative_stock', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
