# Generated by Django 5.2.16 on 2026-07-31 09:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedGoodsTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('transfer_number', models.CharField(max_length=50, unique=True)),
                ('transfer_date', models.DateField()),
                ('dispatch_date', models.DateField(null=True)),
                ('expected_receipt_date', models.DateField(null=True)),
                ('received_date', models.DateField(null=True)),
                ('status', models.CharField(default='DRAFT', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fg_transfers_in', to='locations.location')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fg_transfers_out', to='locations.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinishedGoodsTransferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch', models.CharField(blank=True, max_length=80)),
                ('requested_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('dispatched_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('received_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('damaged_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.finishedproduct')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transfers.finishedgoodstransfer')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.unitofmeasurement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('transfer_number', models.CharField(max_length=50, unique=True)),
                ('transfer_date', models.DateField()),
                ('status', models.CharField(default='DRAFT', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_material_transfers', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_transfers_in', to='locations.location')),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_material_transfers', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_material_transfers', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_material_transfers', to=settings.AUTH_USER_MODEL)),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_transfers_out', to='locations.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialTransferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.rawmaterial')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transfers.materialtransfer')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.unitofmeasurement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
