from django.db import models
from common.models import TransactionalModel,UUIDModel
class SalesInvoice(TransactionalModel):
 invoice_number=models.CharField(max_length=50,unique=True);customer=models.ForeignKey("master_data.Customer",on_delete=models.PROTECT);invoice_date=models.DateField();due_date=models.DateField(null=True);sales_location=models.ForeignKey("locations.Location",on_delete=models.PROTECT);status=models.CharField(max_length=30,default="DRAFT");subtotal=models.DecimalField(max_digits=18,decimal_places=2,default=0);discount_total=models.DecimalField(max_digits=18,decimal_places=2,default=0);vat_total=models.DecimalField(max_digits=18,decimal_places=2,default=0);grand_total=models.DecimalField(max_digits=18,decimal_places=2,default=0);cost_of_goods_sold=models.DecimalField(max_digits=18,decimal_places=2,default=0);gross_profit=models.DecimalField(max_digits=18,decimal_places=2,default=0);gross_margin_percentage=models.DecimalField(max_digits=7,decimal_places=3,default=0);paid_amount=models.DecimalField(max_digits=18,decimal_places=2,default=0);outstanding_amount=models.DecimalField(max_digits=18,decimal_places=2,default=0);payment_terms=models.CharField(max_length=100,blank=True);salesperson=models.ForeignKey("accounts.User",null=True,on_delete=models.SET_NULL,related_name="sales");notes=models.TextField(blank=True)
class SalesInvoiceItem(UUIDModel):
 sales_invoice=models.ForeignKey(SalesInvoice,on_delete=models.CASCADE,related_name="items");finished_product=models.ForeignKey("master_data.FinishedProduct",on_delete=models.PROTECT);batch=models.CharField(max_length=80,blank=True);quantity=models.DecimalField(max_digits=18,decimal_places=3);unit=models.ForeignKey("master_data.UnitOfMeasurement",on_delete=models.PROTECT);selling_price=models.DecimalField(max_digits=18,decimal_places=2);unit_cost_snapshot=models.DecimalField(max_digits=18,decimal_places=4,default=0);discount_amount=models.DecimalField(max_digits=18,decimal_places=2,default=0);tax_rate=models.DecimalField(max_digits=7,decimal_places=4,default=0);tax_amount=models.DecimalField(max_digits=18,decimal_places=2,default=0);line_total=models.DecimalField(max_digits=18,decimal_places=2,default=0);cost_total=models.DecimalField(max_digits=18,decimal_places=2,default=0);gross_profit=models.DecimalField(max_digits=18,decimal_places=2,default=0)
class CustomerLedger(UUIDModel):
 customer=models.ForeignKey("master_data.Customer",on_delete=models.PROTECT);transaction_date=models.DateField();reference_type=models.CharField(max_length=40);reference_id=models.UUIDField();debit=models.DecimalField(max_digits=18,decimal_places=2,default=0);credit=models.DecimalField(max_digits=18,decimal_places=2,default=0);created_at=models.DateTimeField(auto_now_add=True)
class SalesReturn(TransactionalModel):
 return_number=models.CharField(max_length=50,unique=True);customer=models.ForeignKey("master_data.Customer",on_delete=models.PROTECT);original_sales_invoice=models.ForeignKey(SalesInvoice,on_delete=models.PROTECT);return_date=models.DateField();return_location=models.ForeignKey("locations.Location",on_delete=models.PROTECT);reason=models.TextField();status=models.CharField(max_length=30,default="DRAFT");subtotal=models.DecimalField(max_digits=18,decimal_places=2,default=0);vat_total=models.DecimalField(max_digits=18,decimal_places=2,default=0);credit_total=models.DecimalField(max_digits=18,decimal_places=2,default=0);notes=models.TextField(blank=True)
class SalesReturnItem(UUIDModel):
 sales_return=models.ForeignKey(SalesReturn,on_delete=models.CASCADE,related_name="items");original_sales_invoice_item=models.ForeignKey(SalesInvoiceItem,on_delete=models.PROTECT);finished_product=models.ForeignKey("master_data.FinishedProduct",on_delete=models.PROTECT);batch=models.CharField(max_length=80,blank=True);sold_quantity=models.DecimalField(max_digits=18,decimal_places=3);previously_returned_quantity=models.DecimalField(max_digits=18,decimal_places=3,default=0);return_quantity=models.DecimalField(max_digits=18,decimal_places=3);condition=models.CharField(max_length=30,choices=[(x,x.title()) for x in ("SALEABLE","DAMAGED","EXPIRED","QUALITY_ISSUE")]);unit_price=models.DecimalField(max_digits=18,decimal_places=2);credit_amount=models.DecimalField(max_digits=18,decimal_places=2)
