from django.db import models
from common.models import TransactionalModel,UUIDModel
STATUSES=[(x,x.title()) for x in ("DRAFT","APPROVED","POSTED","PARTIALLY_PAID","PAID","OVERDUE","CANCELLED")]
class PurchaseInvoice(TransactionalModel):
 invoice_number=models.CharField(max_length=50,unique=True); supplier=models.ForeignKey("master_data.Supplier",on_delete=models.PROTECT); supplier_invoice_number=models.CharField(max_length=80,blank=True); invoice_date=models.DateField(); due_date=models.DateField(null=True,blank=True); warehouse=models.ForeignKey("locations.Location",on_delete=models.PROTECT); status=models.CharField(max_length=30,choices=STATUSES,default="DRAFT"); subtotal=models.DecimalField(max_digits=18,decimal_places=2,default=0); discount_total=models.DecimalField(max_digits=18,decimal_places=2,default=0); vat_total=models.DecimalField(max_digits=18,decimal_places=2,default=0); grand_total=models.DecimalField(max_digits=18,decimal_places=2,default=0); paid_amount=models.DecimalField(max_digits=18,decimal_places=2,default=0); outstanding_amount=models.DecimalField(max_digits=18,decimal_places=2,default=0); notes=models.TextField(blank=True); attachment=models.FileField(upload_to="purchases/",blank=True)
class PurchaseInvoiceItem(UUIDModel):
 purchase_invoice=models.ForeignKey(PurchaseInvoice,on_delete=models.CASCADE,related_name="items"); raw_material=models.ForeignKey("master_data.RawMaterial",on_delete=models.PROTECT); quantity=models.DecimalField(max_digits=18,decimal_places=3); unit=models.ForeignKey("master_data.UnitOfMeasurement",on_delete=models.PROTECT); purchase_rate=models.DecimalField(max_digits=18,decimal_places=4); discount_amount=models.DecimalField(max_digits=18,decimal_places=2,default=0); tax_rate=models.DecimalField(max_digits=7,decimal_places=4,default=0); tax_amount=models.DecimalField(max_digits=18,decimal_places=2,default=0); line_total=models.DecimalField(max_digits=18,decimal_places=2,default=0)
class SupplierLedger(UUIDModel):
 supplier=models.ForeignKey("master_data.Supplier",on_delete=models.PROTECT); transaction_date=models.DateField(); reference_type=models.CharField(max_length=40); reference_id=models.UUIDField(); debit=models.DecimalField(max_digits=18,decimal_places=2,default=0); credit=models.DecimalField(max_digits=18,decimal_places=2,default=0); created_at=models.DateTimeField(auto_now_add=True)
