from django.db import models
from common.models import TransactionalModel,UUIDModel
class MaterialTransfer(TransactionalModel):
 transfer_number=models.CharField(max_length=50,unique=True);transfer_date=models.DateField();source_location=models.ForeignKey("locations.Location",on_delete=models.PROTECT,related_name="material_transfers_out");destination_location=models.ForeignKey("locations.Location",on_delete=models.PROTECT,related_name="material_transfers_in");status=models.CharField(max_length=30,default="DRAFT");requested_by=models.ForeignKey("accounts.User",null=True,on_delete=models.SET_NULL,related_name="requested_material_transfers");approved_by=models.ForeignKey("accounts.User",null=True,blank=True,on_delete=models.SET_NULL,related_name="approved_material_transfers");dispatched_by=models.ForeignKey("accounts.User",null=True,blank=True,on_delete=models.SET_NULL,related_name="dispatched_material_transfers");received_by=models.ForeignKey("accounts.User",null=True,blank=True,on_delete=models.SET_NULL,related_name="received_material_transfers");notes=models.TextField(blank=True)
class MaterialTransferItem(UUIDModel):
 transfer=models.ForeignKey(MaterialTransfer,on_delete=models.CASCADE,related_name="items");raw_material=models.ForeignKey("master_data.RawMaterial",on_delete=models.PROTECT);quantity=models.DecimalField(max_digits=18,decimal_places=3);dispatched_quantity=models.DecimalField(max_digits=18,decimal_places=3,default=0);received_quantity=models.DecimalField(max_digits=18,decimal_places=3,default=0);damaged_quantity=models.DecimalField(max_digits=18,decimal_places=3,default=0);unit=models.ForeignKey("master_data.UnitOfMeasurement",on_delete=models.PROTECT)
 class Meta:constraints=[models.CheckConstraint(condition=models.Q(quantity__gt=0,dispatched_quantity__gte=0,received_quantity__gte=0,damaged_quantity__gte=0),name="material_transfer_nonnegative"),models.CheckConstraint(condition=models.Q(dispatched_quantity__lte=models.F("quantity")),name="material_dispatch_within_request"),models.CheckConstraint(condition=models.Q(received_quantity__lte=models.F("dispatched_quantity")-models.F("damaged_quantity")),name="material_receipt_within_dispatch")]
class FinishedGoodsTransfer(TransactionalModel):
 transfer_number=models.CharField(max_length=50,unique=True);transfer_date=models.DateField();source_location=models.ForeignKey("locations.Location",on_delete=models.PROTECT,related_name="fg_transfers_out");destination_location=models.ForeignKey("locations.Location",on_delete=models.PROTECT,related_name="fg_transfers_in");dispatch_date=models.DateField(null=True);expected_receipt_date=models.DateField(null=True);received_date=models.DateField(null=True);status=models.CharField(max_length=30,default="DRAFT");notes=models.TextField(blank=True)
class FinishedGoodsTransferItem(UUIDModel):
 transfer=models.ForeignKey(FinishedGoodsTransfer,on_delete=models.CASCADE,related_name="items");finished_product=models.ForeignKey("master_data.FinishedProduct",on_delete=models.PROTECT);batch=models.CharField(max_length=80,blank=True);requested_quantity=models.DecimalField(max_digits=18,decimal_places=3);dispatched_quantity=models.DecimalField(max_digits=18,decimal_places=3,default=0);received_quantity=models.DecimalField(max_digits=18,decimal_places=3,default=0);damaged_quantity=models.DecimalField(max_digits=18,decimal_places=3,default=0);unit=models.ForeignKey("master_data.UnitOfMeasurement",on_delete=models.PROTECT)
 class Meta:constraints=[models.CheckConstraint(condition=models.Q(requested_quantity__gt=0,dispatched_quantity__gte=0,received_quantity__gte=0,damaged_quantity__gte=0),name="fg_transfer_nonnegative"),models.CheckConstraint(condition=models.Q(dispatched_quantity__lte=models.F("requested_quantity")),name="fg_dispatch_within_request"),models.CheckConstraint(condition=models.Q(received_quantity__lte=models.F("dispatched_quantity")-models.F("damaged_quantity")),name="fg_receipt_within_dispatch")]
