# Generated by Django 5.2.16 on 2026-08-04 17:31

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count

def validate_historical_payments(apps,schema_editor):
    for payment_name,allocation_name in (("CustomerPayment","CustomerPaymentAllocation"),("SupplierPayment","SupplierPaymentAllocation")):
        Payment=apps.get_model("payments",payment_name);Allocation=apps.get_model("payments",allocation_name)
        if Payment.objects.filter(amount__lte=0).exists() or Allocation.objects.filter(amount__lte=0).exists():
            raise RuntimeError("Payment migration stopped: historical payment/allocation amounts must be positive. Correct the records before retrying.")
        duplicate=Allocation.objects.values("payment_id","invoice_id").annotate(count=Count("id")).filter(count__gt=1).order_by("payment_id","invoice_id").first()
        if duplicate:
            raise RuntimeError("Payment migration stopped: duplicate historical invoice allocations exist. Consolidate them before retrying.")


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('payments', '0001_initial'),
        ('purchasing', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='payment_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.RunPython(validate_historical_payments,migrations.RunPython.noop),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['customer', 'payment_date', 'status'], name='cust_pay_party_date_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpaymentallocation',
            index=models.Index(fields=['invoice', 'payment'], name='customer_alloc_invoice_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['supplier', 'payment_date', 'status'], name='supp_pay_party_date_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpaymentallocation',
            index=models.Index(fields=['invoice', 'payment'], name='supplier_alloc_invoice_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='customer_payment_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='customerpaymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='customer_allocation_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='customerpaymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'invoice'), name='unique_customer_payment_invoice'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='supplier_payment_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='supplierpaymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='supplier_allocation_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='supplierpaymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'invoice'), name='unique_supplier_payment_invoice'),
        ),
    ]
