# Generated by Django 5.2.16 on 2026-07-31 09:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('location_type', models.CharField(choices=[('RAW_MATERIAL_WAREHOUSE', 'Raw Material Warehouse'), ('PRODUCTION', 'Production'), ('FINISHED_GOODS_WAREHOUSE', 'Finished Goods Warehouse'), ('SHOP', 'Shop'), ('DELIVERY_VAN', 'Delivery Van'), ('DAMAGED_GOODS', 'Damaged Goods'), ('IN_TRANSIT', 'In Transit'), ('OTHER', 'Other')], max_length=40)),
                ('address', models.TextField(blank=True)),
                ('is_sales_location', models.BooleanField(default=False)),
                ('is_inventory_location', models.BooleanField(default=True)),
                ('is_production_location', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
