# Generated by Django 5.2.16 on 2026-07-31 09:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_number', models.CharField(max_length=80, unique=True)),
                ('transaction_date', models.DateTimeField()),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('PURCHASE_REVERSAL', 'Purchase Reversal'), ('RAW_MATERIAL_TRANSFER_OUT', 'Raw Material Transfer Out'), ('RAW_MATERIAL_TRANSFER_IN', 'Raw Material Transfer In'), ('PRODUCTION_CONSUMPTION', 'Production Consumption'), ('PRODUCTION_OUTPUT', 'Production Output'), ('FINISHED_GOODS_TRANSFER_OUT', 'Finished Goods Transfer Out'), ('FINISHED_GOODS_TRANSFER_IN', 'Finished Goods Transfer In'), ('IN_TRANSIT_OUT', 'In Transit Out'), ('IN_TRANSIT_IN', 'In Transit In'), ('SALE', 'Sale'), ('SALE_REVERSAL', 'Sale Reversal'), ('SALES_RETURN', 'Sales Return'), ('WASTAGE', 'Wastage'), ('DAMAGE', 'Damage'), ('EXPIRY', 'Expiry'), ('STOCK_ADJUSTMENT_IN', 'Stock Adjustment In'), ('STOCK_ADJUSTMENT_OUT', 'Stock Adjustment Out')], max_length=40)),
                ('reference_type', models.CharField(max_length=80)),
                ('reference_id', models.UUIDField()),
                ('batch', models.CharField(blank=True, max_length=100)),
                ('quantity_in', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('quantity_out', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reversal', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_in_transactions', to='locations.location')),
                ('finished_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.finishedproduct')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.rawmaterial')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='inventory.stocktransaction')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_out_transactions', to='locations.location')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.unitofmeasurement')),
            ],
            options={
                'indexes': [models.Index(fields=['raw_material', 'destination_location'], name='inventory_s_raw_mat_bff43e_idx'), models.Index(fields=['finished_product', 'destination_location', 'batch'], name='inventory_s_finishe_be362b_idx'), models.Index(fields=['reference_type', 'reference_id'], name='inventory_s_referen_e50b9e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('finished_product__isnull', True), ('raw_material__isnull', False)), models.Q(('finished_product__isnull', False), ('raw_material__isnull', True)), _connector='OR'), name='stock_exactly_one_item'), models.CheckConstraint(condition=models.Q(('quantity_in__gte', 0), ('quantity_out__gte', 0)), name='stock_nonnegative_quantities')],
            },
        ),
    ]
