# Generated by Django 5.2.16 on 2026-08-04 16:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventory_balance_and_performance_indexes'),
        ('locations', '0001_initial'),
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('OPENING_STOCK', 'Opening Stock'), ('OPENING_STOCK_REVERSAL', 'Opening Stock Reversal'), ('PURCHASE', 'Purchase'), ('PURCHASE_REVERSAL', 'Purchase Reversal'), ('RAW_MATERIAL_TRANSFER_OUT', 'Raw Material Transfer Out'), ('RAW_MATERIAL_TRANSFER_IN', 'Raw Material Transfer In'), ('PRODUCTION_CONSUMPTION', 'Production Consumption'), ('PRODUCTION_OUTPUT', 'Production Output'), ('FINISHED_GOODS_TRANSFER_OUT', 'Finished Goods Transfer Out'), ('FINISHED_GOODS_TRANSFER_IN', 'Finished Goods Transfer In'), ('IN_TRANSIT_OUT', 'In Transit Out'), ('IN_TRANSIT_IN', 'In Transit In'), ('SALE', 'Sale'), ('SALE_REVERSAL', 'Sale Reversal'), ('SALES_RETURN', 'Sales Return'), ('WASTAGE', 'Wastage'), ('WASTAGE_REVERSAL', 'Wastage Reversal'), ('DAMAGE', 'Damage'), ('EXPIRY', 'Expiry'), ('STOCK_ADJUSTMENT_IN', 'Stock Adjustment In'), ('STOCK_ADJUSTMENT_OUT', 'Stock Adjustment Out')], max_length=40),
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total_value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('reason', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('adjustment_number', models.CharField(editable=False, max_length=80, unique=True)),
                ('adjustment_date', models.DateField()),
                ('direction', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative')], max_length=10)),
                ('previous_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('resulting_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('finished_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.finishedproduct')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.location')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.rawmaterial')),
                ('reversal_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.stocktransaction')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.unitofmeasurement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('finished_product__isnull', True), ('raw_material__isnull', False)), models.Q(('finished_product__isnull', False), ('raw_material__isnull', True)), _connector='OR'), name='stockadjustment_exactly_one_item'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stockadjustment_positive_quantity')],
            },
        ),
        migrations.CreateModel(
            name='WastageDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total_value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('reason', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('document_number', models.CharField(editable=False, max_length=80, unique=True)),
                ('wastage_date', models.DateField()),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('finished_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.finishedproduct')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.location')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.rawmaterial')),
                ('reversal_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.stocktransaction')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.unitofmeasurement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('finished_product__isnull', True), ('raw_material__isnull', False)), models.Q(('finished_product__isnull', False), ('raw_material__isnull', True)), _connector='OR'), name='wastagedocument_exactly_one_item'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='wastagedocument_positive_quantity')],
            },
        ),
    ]
