from django.db import models
from common.models import TransactionalModel,UUIDModel
class ProductionBatch(TransactionalModel):
 production_number=models.CharField(max_length=50,unique=True);finished_product=models.ForeignKey("master_data.FinishedProduct",on_delete=models.PROTECT);recipe=models.ForeignKey("recipes.Recipe",on_delete=models.PROTECT);recipe_version=models.CharField(max_length=30,blank=True);planned_quantity=models.DecimalField(max_digits=18,decimal_places=3);actual_produced_quantity=models.DecimalField(max_digits=18,decimal_places=3,default=0);production_location=models.ForeignKey("locations.Location",on_delete=models.PROTECT,related_name="production_batches");finished_goods_destination=models.ForeignKey("locations.Location",on_delete=models.PROTECT,related_name="production_outputs");batch_number=models.CharField(max_length=80);manufacturing_date=models.DateField();expiry_date=models.DateField(null=True,blank=True);supervisor=models.ForeignKey("accounts.User",null=True,blank=True,on_delete=models.SET_NULL,related_name="supervised_batches");status=models.CharField(max_length=30,default="DRAFT");material_cost=models.DecimalField(max_digits=18,decimal_places=2,default=0);additional_cost=models.DecimalField(max_digits=18,decimal_places=2,default=0);total_production_cost=models.DecimalField(max_digits=18,decimal_places=2,default=0);cost_per_unit=models.DecimalField(max_digits=18,decimal_places=4,default=0);remarks=models.TextField(blank=True)
class ProductionConsumption(UUIDModel):
 production_batch=models.ForeignKey(ProductionBatch,on_delete=models.CASCADE,related_name="consumptions");raw_material=models.ForeignKey("master_data.RawMaterial",on_delete=models.PROTECT);standard_required_quantity=models.DecimalField(max_digits=18,decimal_places=3);actual_consumed_quantity=models.DecimalField(max_digits=18,decimal_places=3);unit=models.ForeignKey("master_data.UnitOfMeasurement",on_delete=models.PROTECT);unit_cost=models.DecimalField(max_digits=18,decimal_places=4);total_cost=models.DecimalField(max_digits=18,decimal_places=2);variance_quantity=models.DecimalField(max_digits=18,decimal_places=3,default=0)
class ProductionOutput(UUIDModel):
 production_batch=models.ForeignKey(ProductionBatch,on_delete=models.CASCADE,related_name="outputs");quantity=models.DecimalField(max_digits=18,decimal_places=3);unit_cost=models.DecimalField(max_digits=18,decimal_places=4)
class ProductionWastage(UUIDModel):
 production_batch=models.ForeignKey(ProductionBatch,on_delete=models.CASCADE,related_name="wastages");raw_material=models.ForeignKey("master_data.RawMaterial",null=True,blank=True,on_delete=models.PROTECT);finished_product=models.ForeignKey("master_data.FinishedProduct",null=True,blank=True,on_delete=models.PROTECT);quantity=models.DecimalField(max_digits=18,decimal_places=3);reason=models.TextField()
