# Generated by Django 5.2.16 on 2026-07-31 09:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe_number', models.CharField(max_length=50, unique=True)),
                ('standard_output_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('version', models.CharField(max_length=30)),
                ('effective_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.finishedproduct')),
                ('output_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.unitofmeasurement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('wastage_percentage', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.rawmaterial')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recipes.recipe')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.unitofmeasurement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('status', 'ACTIVE')), fields=('finished_product',), name='one_default_active_recipe'),
        ),
    ]
